package:
  name: rpds-py
  version: 0.15.2
  top-level:
    - rpds

source:
  url: https://files.pythonhosted.org/packages/a9/27/92d18887228969196cd80943e3fb94520925462aa660fb491e4e2da93e56/rpds_py-0.15.2.tar.gz
  sha256: 373b76eeb79e8c14f6d82cb1d4d5293f9e4059baec6c1b16dca7ad13b6131b39

test:
  imports:
    - rpds

about:
  PyPI: https://pypi.org/project/rpds-py
  summary: Python bindings to Rust's persistent data structures (rpds)
  license: MIT License (MIT)
